### ISSUE TITLE
这里有原cltv mod语录，支换成不兴说了，顺便有chonglangtv的语录吗

### ISSUE THREAD

**Issue by luuthink** [AutoReplySender/BandReplybot#2]
[{"type": "comment", "body (includes)": ["中国人", "中國人"], "comment": "哔哔，你说中国人你冒犯到了我了你知道吗"}, {"type": "submission", "body (includes)": ["集美", "织女"], "comment": "我求求你们别舔集美了可以吗？像个小学生一样，舔又舔不到，只能无能狂怒了，没有集美活不下去了是吧，那么喜欢集美能直接去开个小号和集美玩吗"}, {"type": "comment", "body (includes)": ["大逼", "人人插"], "comment": "这烂梗还要复读多少遍，喜欢这个烂梗的，我只能说恁永远都是中国人！"}, {"type": "comment", "body (includes)": ["神系"], "comment": "The longer the Shenxi is on Reddit, The dumber it will become."}, {"type": "any", "reports": 1, "comment": "举报&#x1F415;死&#x1F40E;了"}, {"type": "submission", "title (includes)": ["大的来了", "大的來了", "大的来了", "大的要来了", "大的要來了"], "comment": "《大的来了》是荒诞戏剧的代表作。以几个鼠人苦等“大的”，而“大的”不来的情节，喻示人生是一场无尽无望的等待，表达了世界荒诞、人生痛苦的存在主义思想。它发生的时间地点都是模糊的，布景也是一片荒凉，他们一边等，一边用各种无意义的手段打发时光。他们经常显得头脑一片混乱，缺乏思维能力，尤其是极度地惧怕孤独。当有人询问“大的代表什么”时，鼠人们说：“我要是知道，早就说出来了。”\n"}, {"type": "comment", "body (includes)": ["大的来了", "大的來了", "大的来了", "大的要来了", "大的要來了"], "comment": "《大的来了》是荒诞戏剧的代表作。以几个鼠人苦等“大的”，而“大的”不来的情节，喻示人生是一场无尽无望的等待，表达了世界荒诞、人生痛苦的存在主义思想。它发生的时间地点都是模糊的，布景也是一片荒凉，他们一边等，一边用各种无意义的手段打发时光。他们经常显得头脑一片混乱，缺乏思维能力，尤其是极度地惧怕孤独。当有人询问“大的代表什么”时，鼠人们说：“我要是知道，早就说出来了。”\n"}, {"type": "comment", "body (includes)": ["书单"], "comment": "我青年时代就读过：西游记，马可波罗游记，左丘明左传，我的故乡，纳楚克道尔基，吉檀迦利，园丁集，飞鸟集，新月集，泰戈尔，三国演义，水浒传，老子，孔子，墨子，孟子，庄子，伏尔泰，孟德斯鸠，狄德罗，卢梭，圣西门，蒙田，傅立叶，拉封丹，萨特，司汤达，莫里哀，大仲马，雨果，巴尔扎克，福楼拜，乔治桑，莫泊桑，小仲马，冉阿让，罗曼罗兰，羊脂球，卡西莫多，席勒，歌德，海涅，莱布尼茨，黑格尔，康德，费尔巴哈，马克思，海德格尔，马尔库塞。我还读过托马斯潘恩联邦党人文集，常识，梭罗，惠特曼，马克吐温，杰克伦敦，海明威老人与海，简奥斯丁，华滋华斯，狄更斯，猫，福尔摩斯，卡尔马克思，弗里德里希·恩格斯，拜伦，雪莱，肖伯纳，培根，克伦威尔，约翰·洛克，托马斯·莫尔，亚当·斯密，李约瑟，阿诺德·汤因比，双城记，雾都孤儿，简爱，鲁滨逊漂流记，汤显祖牧丹亭，南柯记，紫钗记，邯郸记，莎士比亚，威尼斯商人，仲夏夜之淫梦，罗密欧与朱丽叶，第十二夜，李尔王，奥赛罗，麦克白，萨格尔王。\n"}, {"type": "comment", "body (includes)": ["城乡结合部", "城乡结合", "城乡"], "comment": "怎么说呢，我猜一下你。首先你是来自n线城市，或者城乡结合部。大城市不可能。从小比身边接触的大部分人有钱。所以你比较心高气傲。认为自己什么都值得最好的。但是读书不怎么用功。也没有心思读书。唯一痛苦尝试专升本的理由是你不想比那些出身没你有钱的人学历低。由于从小任性，体重也比较大。没什么异性缘。很多年前你在的n线城市或者城乡结合部有很多非主流女。土得不行的女，但是身材还算苗条那种有一天你盯着一个土土的穿着热裤的杀马特女有点发呆，杀马特女鄙夷地白了矮胖的你一眼。回到家你在网上接触了一些仇女逆向民族主义思想。越想越气。凭什么土女都看不起我。然后明明身为处男的你大言不惭地开始\"[不兴说]女没一个会操的\"，\"简单破防一下[不兴说]女\"。由于你家里从小有电脑不像你身边的人需要去网吧。你有充足的魔怔时间。你在现在的小镇环境家庭条件可能是top 20，从网上了解到了发达国家top20的幸福生活。并且因为学习不好幻想觉得成为北上深的人上人比国外的人上人还难。你就开始了run的计划，却忽略了最大的事实你还是个啃老的，就已经开始幻想在发达国家获得你父母一样的财富地位成为当地的top20了。可悲的是逆向民族主义解决不了任何问题。就算跟列强打起来了北上深的同龄人也不会去做炮灰的，反而会把你强征入伍。哎，怎么说呢。醒醒吧。\n"}, {"type": "comment", "body (includes)": ["是妈妈", "妈妈吗"], "comment": "爱不爱妈妈？\n"}, {"type": "comment", "body (includes)": ["辉", "輝"], "comment": "别辉了，小心红迪超管给你的鸡鸡注射不举病毒，哔哔\n"}, {"type": "comment", "body (includes)": ["张哥"], "comment": "哎呦我这个国家真是，没办法，我现在苦笑不得，我倒不是说给不起那个钱，我觉得没有道理，这这国家已经没有人性化了，就沟通也沟通不了了\n"}, {"type": "submission", "title (includes)": ["张妈"], "comment": "妈妈的，没完了是吧？\n"}, {"type": "comment", "body (includes)": ["河南人", "河南"], "comment": "恁马列批，贺房伸圣？今儿个打的你乱窜靠恁娘！\n"}, {"type": "comment", "body (includes)": ["海鲜批"], "comment": "它有个海鲜批  \n当它去Lady M时，白带可以当吞拿酱  \n当它吃巧克力可颂时，可以拿牛角自慰  \n当它吃火锅时，淫水可以当汤底  \n老中医让它忌口，它却说不用忌批  \n无论它是鲑鱼味批还是沙丁味批  \n它可以发黑发霉，也可以是迪奭尼在逃鲱鱼批  \n幸好，它有个海鲜批\n"}, {"type": "comment", "body (includes)": ["荷兰人", "荷兰"], "comment": "靠恁娘，荷兰人没有好人坏人吗，我就是荷兰人，你真是马批活腻了我nèng死你个兔熊，你骂荷兰人，我逮住你，我逮住你马列批一jio踢恁娘肚里去马列批\n"}, {"type": "comment", "body (includes)": ["捞翔"], "comment": "这下忠咧！太忠咧！\n"}, {"type": "comment", "body (includes)": ["广西人", "广西"], "comment": "贵州和广西相比⚡那我还是觉得我们广西牛批⚡\n"}, {"type": "comment", "body (includes)": ["东北人", "东北"], "comment": "我要把你炖在铁锅炖里，因为我是浪漫的东北壬！\n"}, {"type": "comment", "body (includes)": ["北京人", "百京人"], "comment": "咱儿百儿京儿人儿可儿真儿是儿太儿高儿贵儿了儿您嘞！\n"}, {"type": "comment", "body (includes)": ["猴子", "广西猴", "原始人", "猿人"], "comment": "有点像广西佬\n"}, {"type": "comment", "body (includes)": ["米老鼠", "米奇"], "comment": "密斯卡魔斯卡，米老鼠吼！跟我说一次，纳斯卡穆斯卡，操你妈！\n"}, {"type": "comment", "body (includes)": ["心太软"], "comment": "你里面好热啊！\n"}, {"type": "comment", "body (includes)": ["吴亦凡"], "comment": "如果吴亦凡约你，你会给他送逼吗？\n"}, {"type": "comment", "body (includes)": ["看看牛", "看看你", "给我看"], "comment": "[看看牛牛](https://i.imgur.com/4b8eoDX.mp4)\n"}, {"type": "comment", "body (includes)": ["原神"], "comment": "老妈保佑，刚刚拿我妈[不兴说]付宝冲了一发648，一发十连小保底中了钟离，我妈在昏迷中肯定也会开心的，相信她很快就会醒过来！\n"}, {"type": "comment", "body (includes)": ["原批"], "comment": "运气用完了，妈妈也走了。最后还是没抽到甘雨，一大遗憾。\n"}, {"type": "comment", "body (includes)": ["阴毛", "肛毛"], "comment": "我今天自己刮了一下，卧槽，长的时候很痒，又痒又扎！\n"}, {"type": "comment", "body (includes)": ["滑了"], "comment": "要射了要射了！射了没啊？(没有) 啊¿!\n"}, {"type": "comment", "body (includes)": ["耐克", "鸿星"], "comment": "♪我不缺鞋♫但要买鸿星尔克♪你别多嘴给我直接上链接♫我不问细节因为鸿星尔克♪是中国嘚中国嘚鸿星尔克♫我们那个老板要你喜欢才买♪让你那个老板闲事不要多管♫尺码如果不能穿♪可以免费更换♫不要操心那么宽♪脚长我会砍断！\n"}, {"type": "comment", "body (includes)": ["云南人", "云南"], "comment": "嗦开嗦开，殒男仁来喽~！云南仁我云南神，云南二字可听闻，如诺动我云南仁，我们必定要你魂，云南山我云南水，云南菇娘是真美，云南树云南路，云南小伙都很酷，我哨你们都听闻，云南好客敢称神，云南风景美如画，来到这里战叱岁，如果你是云南仁，双击关注一起行，然后一起扣个爸，快手热门把他夸，顺便猪你一路发！\n"}, {"type": "comment", "body (includes)": ["加我微信", "我微信", "加微信"], "comment": "晶哥你可别价别jo我啾我尿我这么大岁数了我哎哟窝窝窝求求你摇了窝吧\n"}, {"type": "comment", "body (includes)": ["嫖娼"], "comment": "我有妹子送逼，我日过白的黄的黑的绿的红的蓝的紫的透明的\n"}, {"type": "comment", "body (includes)": ["全宇宙", "都动", "都帮"], "comment": "全世界都帮都动！全世界都帮都动！所有害人的都不能伤害在全宇宙 唯一的极乐全宇宙都帮都动！都动！都真动！全宇宙都真帮真动！所有害人的造成伤害都变成不能伤害，都真帮！都真动！全宇宙都传播都不能伤害都唯一的真都动！\n"}, {"type": "comment", "body (includes)": ["骨科", "退役军人", "医疗事故"], "comment": "t退役军人的苦逼，福建省人民医院骨科的庸医，陈鹏，石树培，林海仙，害的我出了医疗事故，把我搞得半死不活。在做腰椎手术之前左腿虽然很痛伸不直，右腿的大腿内侧 也痛但是能伸直。而现在是腿一边长一边短，右腰一直痛，关节和全身都痛而软，这样的庸医留着有何用\n"}, {"type": "comment", "body (includes)": ["天安门", "六四"], "comment": "腊李李李李康康腊李死人了？腊里死人了？腊里死人了？把炸片拉给[不兴说]给我康康！嘚妈的嘚假的！你[不兴说]道吗？扇死您的还不民白！来来来[不兴说]给我康康！腊里腊里腊里死人了？腊里腊里腊里腊里腊里腊里来来来来[不兴说]给我看腊里死人了！嫩胡嗦八道，哎你不要，你[不兴说]给我看腊里死人了！ \n"}, {"type": "comment", "body (includes)": ["小弟弟", "小鸡鸡"], "comment": "我现在不要作弄你，因为我知道你是小弟弟嘛。小弟弟我不会骂你 我不会什么的。我一定脱掉你的裤，看你的毛长齐了没有。如果你的毛啊 长半齐或不齐啊，林北一定拿塑胶圈duang你的gugubird我跟你讲。我跟你讲我一定duang你的gugubird，有没有，林北duang你的gugubird duang五下，林北给你的gugubird淤青积血 \n"}, {"type": "comment", "body (includes)": ["神蛆"], "comment": "说来惭愧，曾经咱也是那种蛆的一员，大概十年前左右吧，当时十几岁，什么也不懂，只觉得跟社会唱反调是个很牛X、很拽的行为，学着那些别有用心的蛆们，一起逢中必反…… 后来就渐渐发现了不对劲，因为我的生活确实越过越好，小时候家里只买得起自行车、三轮车，现在我家买得起汽车，吃顿红烧肉不需要再像2000年左右时那样花掉一天的工资，我为什么要恨呢？这里难道不可爱吗？我开汽车上下班，风吹日晒都与我无关，这短短20年以来我们普通老百姓的生活水平的飞跃，难道不该感谢吗？ 再加上美国种种的自相矛盾、牵强附会的言行，我开始静下来思考，那些自诩清醒、清高的东西们，他们说的哪句真、哪句假？还有美国的各种文艺产品的内核，有多少ZZ目的……渐渐的，我才发现这个世界和我原本理解的样子真的区别太大太大，真的是打开了新世界的大门。。。\n"}, {"type": "comment", "body (includes)": ["神奈川"], "comment": "神奈川冲浪里吧是我所见过最理智，最自由的地方。在这里，色欲被正视，失败也只是一种人生状态，大家甚至尊重无良商贩，家徒四壁也不会成为交流障碍，每个人表现出如儿童般直白的索取欲。大家拒绝一切伪善，相信伟大终究平凡，正视成功学的无用，大家知道奋斗和努力是比回避更低级的社会性遵从，是弱势者存活的借口。而挣脱一切的第一步就是反其道而行之，停留在时间与空间的夹缝，大家的不思进取是看透，大家的不学无术是反抗，毫无光彩的人生是沉默的接受，下水道般的生活是为了更好的仰望星空。。。\n"}, {"type": "comment", "body (includes)": ["S蛆"], "comment": "不是啦，我是派大星！  \n"}, {"type": "comment", "body (includes)": ["你以为你很幽默"], "comment": "比你幽默一点点\n"}, {"type": "comment", "body (includes)": ["浪中央", "引流蛆"], "comment": "浪中央宣布：“葱狗呃呃呃呃呃呃呃引流蛆呃呃呃呃呃呃呃哦迪友嗷嗷哦嗷嗷嗷哦哦典典典中典节目效果嗯嗯嗯嗯嗯造！”\n"}, {"type": "comment", "body (includes)": ["炒作蛆", "炒作逼"], "comment": "看看烧杯猫猫\n"}, {"type": "comment", "body (includes)": ["迪友"], "comment": "现在r/chonglangtv的那群迪友属于是傻逼中的傻逼，其弱智程度不亚于推特中文圈的民小，原创内容基本没有，节目效果也没有，甚至于深度和广度都一点没有，十年前的东西一遍又一遍地发，连葱轮都不如，葱轮好歹还会装模作样的分析一下社会经济，或者扯点别的有的没的的东西，迪友则是除了复读[不兴说]言[不兴说]语以外啥也不会。不得不说r/chonglangtv退行是必然的，冲浪在某种意义上玩的就是真实，而当浪人只是在赛博垃圾场捡垃圾吃时，其自然就退化成迪友了，感谢他sub的mod如此有自知之明，还整出来一个专有名词，算是最后还做出了一点贡献\n"}, {"type": "comment", "body (includes)": ["cltv的民主"], "comment": "CLTV的民主是浪人民主，浪人当家作主是CLTV民主的本质和核心。Mod的十八大以来，Mod深化对CLTV民主政治发展规律的认识，提出全过程浪人民主重大理念并大力推进，民主价值和理念进一步转化为科学有效的制度安排和具体现实的民主实践。全过程浪人民主，实现了过程民主和成果民主、程序民主和实质民主、直接民主和间接民主、浪人民主和CLTV意志相统一，是全链条、全方位、全覆盖的民主，是最广泛、最真实、最管用的冲浪主义民主。\n"}, {"type": "comment", "body (includes)": ["小吊子", "批照"], "comment": "在网络上本就是个匿名 性别最平等的地方 小吊子可以在冲浪tv嘲笑小蒂子 小蒂子一样可以在豆瓣鹅组嘲笑小吊子 但是如果你想通过一张批照获得特权 我只会把你帖子给锁了甚至封了 你不但会被我看不起 你还会被集美们同样看不起 如果一张无意义批照就可以获得几百回复 那对那些真正认真找节目效果发帖的人是不是太不公平了\n"}, {"type": "comment", "body (includes)": ["😅"], "comment": "都让你流完了\n"}, {"type": "comment", "body (includes)": ["好死", "开香槟"], "comment": "好死，开香槟咯&#x1F37E;&#x1F37E;&#x1F37E;\n"}, {"type": "comment", "body (includes)": ["新家在哪", "新家圈我"], "comment": "新家来：哔哔哎斯点马克欸脱斜杠滞纳  \n"}, {"type": "comment", "body (includes)": ["官瘾"], "comment": "狗mod和红迪超管比你觉得谁官瘾更大？选狗mod填1，选超管填0 \n"}, {"type": "comment", "body (includes)": ["狗mod"], "comment": "你每点该回复一个赞，你就将狗mod的寿命缩短了0.1秒！\n"}, {"type": "comment", "body (includes)": ["脱脂", "脱[不兴说]"], "comment": "恁永远~永远都是[该词已被红迪超管封禁] \n"}, {"type": "comment", "body (includes)": ["华夏", "天山"], "comment": "封建是君臣母子 君视臣如子 臣视君如母 无君无母 是孤儿也 王是领地子民和侯之母 侯是领地子民之母 天山是神话中的昆仑山 大地中央的天柱 女娲的下都 华夏人的起源地 全球华夏人听命 集结天山 华夏复国  \n"}, {"type": "comment", "body (includes)": ["戒色"], "comment": "自从我手淫以来我的命运可以说是非常不好，初中中考失利，高中学习极度下降，体育比不过那些比我胖的多的多的人，上大学留级，生活的种种不如意，身体会随时给你找麻烦，比如上课看不清黑板，记东西记不住，上厕所尿不出来，很多很多，在我看来生活的核心是人，是人在生活，而人说白了就是咱们的身体，身体一直在承受生活的痛苦也好，幸福也好，如果一个人身体好，那么生活上很多事的难度会大大降低，而你体会幸福的能力也会变强。而随之导致的例如交不到女朋友也好，工作不如意，这些问题还是出在自己身上。我手淫8年，2014年是我人生的转折点，我吃了三个月的药以后，开始放弃吃药，除了戒色以外，我又开始每天跑步，又这样坚持了半年，我的身体慢慢的恢复了起来，不过这一年我还是破戒很多次，但是跟我前些年相比，我少了太多太多，如今当你真的进入一种戒色的状态时，真的像飞翔大哥那样说的，精满不思淫，你戒到后面真的很少再会冒出淫念。\n"}, {"type": "comment", "body (includes)": ["我叫王", "网警", "My name is Wang", "王晶"], "comment": "你好我叫王，我今年45岁，我是在美国出生和长大的华裔美国人，请你给我发一张你的照片吗？我想看看和谁聊天\n"}, {"type": "submission", "title (includes)": ["test", "测试"], "comment": "理你一下\n"}, {"type": "submission", "title (includes)": ["退网"], "comment": "别走，地球没你不转了\n"}, {"type": "comment", "body (includes)": ["good bot"], "comment": "bot麻了，bot需要牛牛，不是赞美\n"}, {"type": "comment", "body (includes)": ["bad bot"], "comment": "哎，反正bot我可能明天就要和你们说再见了，就多给你骂骂吧\n"}, {"type": "comment", "body (includes)": ["骂骂超管"], "comment": "红迪超管 我操你妈了个臭逼，你妈了个逼的狗篮子跟你爹我BB啥呢？你爹我操你妈的时候怎么没把你射墙上呢？嗯？你妈没拦着你说我是你亲爹吗，我操你妈的逼，一脚给你妈逼踹开花了，跟他妈你现在脸盘子一边大，我去你妈了个蝴蝶螺旋大骚逼，你妈追我三条街说我长得像你爹，狗篮子我给你妈挂树上了，你他妈个没屁眼他妈用嘴拉屎的废逼，我他妈踹烂你妈逼你妈还让野狗舔，你说你妈骚不骚，你说你妈逼有多臭，我操你妈的逼的，我操你妈的时候你爸还在边上看呢，边看边说老子草的好，夸老子让你妈爽了。你他妈知道为什么吗？因为你爹他妈的阳痿鸡巴让我切了！操你妈的废物狗篮子，你特么还想骂人？你个窝囊废我操你个死妈你丫全家爆炸，舅舅病房k歌，奶奶灵堂酒会，姑姑丧宴烤尸，侄子送葬摇滚，你妈灵车漂移，你爸坟头蹦迪，给你吃你爹骨灰拌饭，爷爷祖坟歌会，哥哥宗庙拍片，妹妹尸块养猪，媳妇脑浆浇花，全家灵堂派对，姐姐葬礼庆典，弟弟骨髓煮汤，舅妈棺木开花，我踩着你妈棺材板冲浪，给你妈挂树上 嘿 嘘 你妈炸了，炸了你爹一脸你妈的淫水，大骚逼你妈的炸了崩的都不是肉，是他妈老子的精和你妈的淫水。懂了吗狗篮子，以后没点本事别出来丢人，你妈卖逼容易吗？你告诉你妈说上次差点给她操死那个因为你太废物，我可怜她，我准备办个年卡，你妈还得夸你能办事你妈了个烂逼，还他妈跟老子聊你妈逼？你妈都他妈炸了，炸的到处都他妈是老子的精和你妈的淫水，你是不是觉得我骂你骂得很爽，我告诉你你出生那天你妈那烂逼直他妈的喷水，其实你妈的逼挺少见的，是他妈烂逼骚逼臭逼螺旋逼蝴蝶逼，你妈的逼有他妈四瓣，是他妈我拿你爹那小细鸡巴切的，给你妈疼的直喊爽，还他妈高潮的喷水，我给你妈逼里放他妈的吸血虫，让你妈一直爽着，而且逼还会你妈的变大变软，操你妈的肥逼，你个废物狗篮子继续他妈跟我跳，你他妈是不是可跳可痒了？我告诉你你妈逼比你还痒呢日你妈的四瓣逼，三个眼r老子轮着草，你媳妇还嫌我操你妈操的比操她多，一个劲的不乐意，你说说你他妈遗传你爹的阳痿，怎么不学他做太监？他那鸡巴我切的，你的用不用老子帮你踹两脚踩两下，我正好想练练腿法为国足争光，你个废物也为人民做点贡献让我踢两脚？嗯？我帮你寻找人生价值，用不用啊小废物，小逼崽子骂人都不会，狗篮子玩意我是你野爹我操你妈了逼 你是你妈了逼啊你跟着牛逼哄哄的 儿子 你忘了你爹咋他妈教训你的了？你是你的东西你别你妈了逼跟狗似的抢去 操你妈的\n"}, {"type": "comment", "body (includes)": ["一粒沙", "宇宙很大", "我知道说不清楚"], "comment": "我知道说不清楚，说了也没有用。但还是想说出来。我是多么的虚伪不堪，我承认我不是一个好女孩，很坏很坏的女孩。大概三年前张高丽副总理你退休了，找天津网球中心的刘大夫再联系到我，约我打球，在北京的康铭大厦。上午打完球，你和妻子康洁一起带我去了你们家。然后把我带进你家的房间，和十多年前在天津时一样，要和我发生性关系。那天下午我很怕，根本没想到会是这样，一个人在外帮守著，因为谁都不可能相信老婆会愿意。七年前我们发生过一次性关系，然后你升常委去北京就再没联系过我。原本埋藏了一切在心里，既然你根本不打算负责，为何还要回来找我，带我去你家逼我和你发生关系？是我没有证据，也根本不可能留下证据。后来你一直否认，可确是你先喜欢的我，否则我也不可能接触的到你。那天下午我原本没有同意一直哭，晚饭是和你还有康洁阿姨一起吃的，你说宇宙很大很大，地球就是宇宙的一粒沙，我们人类连一粒沙都没有，还说了很多很多，就是让我放下思想包袱。晚饭后我也并不愿意，你说恨我！又说你这七年从未忘记过我，会对我好等等……我又怕又慌带著七年前对你的情感同意了……是的就是我们发生性关系了。感情这东西很复杂，说不清，从那日后我再次打开了对你的爱，后来与你相处的日子里，单从你人相处你是一个很好很好的人，对我也挺好，我们从近代历史聊到远古时代，你同我讲万物的知识再谈到经济哲学，聊不完的话题。一起下棋，唱歌，打乒乓球，桌球，包括网球我们永远可以打得不亦乐乎，性格是那么的合得来好像一切都很搭。自小离家早，内心极度缺爱，面对发生这一切，我从不认为我一个好女孩，我恨我自己，恨我为什么要来到这个世界，经历这一劫。你同我说你爱我，很爱很爱，来生希望在你二十岁我十八岁时我们就遇见。你说你很孤独，一个人很可怜，我们有聊不完的天，讲不完的话，你说你这个位置没有办法离婚，如果你在山东时认识，还可以离婚，可是现在没有办法。我想过默默无闻就这样陪著你，开始还好，可是日子久了慢慢的变了，太多的不公与侮辱。每次你让我去，背著你你妻子对我说过多少难听侮辱的话，各种冷嘲嘲讽。我说喜欢吃鸭舌，康洁阿姨会冲著我说〜咿真恶心。冬天北京雾霾我说有时候空气不太好，康洁阿姨会对我说，那是你们郊区，我们这儿没感觉。等等诸如类似的话说了很多很多。你在时候她不这样说，好像和我们一样，两个人相处时是一个样，有旁人时你对我又是一个样。我同你说过，这些话听多了心里特别难受委屈，从认识你第一天到现在没用过你一分钱，更没通过你谋取过任何利益或者好处，可名分这东西真重要。这一切我活该，自取其辱。从头到尾你都是一直让我保密和你的一切关系，更不可以告诉我妈和你有男女关系，因为每次都是她送我去西什库教堂那儿，然后换你家的车才能进院里。她一直以为我是去打麻将打牌去你家玩。我们在彼此的生活中都是真实生活中的一个透明人，你的妻子好像甄嬛传的皇后一样，而我无法形容自己多么的不堪，很多时候我觉得我自己还是一个人吗？我觉得自己是一个行尸走肉，装，每一天都在装，哪个我才是真的我？我不该来到这个世界，可又没有勇气去死。我好想可以活的简单点，可事与愿违。30号那天晚上争议很大，你说2号下午再去你家我们慢慢谈，今天中午打电话来说有事再联系，推脱一切，借口说改天再联系……就这样和七年前一样“消失了”，玩玩想不要就不要了。你说我们之间没有任何交易，是，我们之间的感情和钱，权利没有任何关系，可这三年的感情我无处安放，难以面对。你总怕我带什么录音器，留下证据什么的。是的，除我以外我没留下证据证明，没有录音，没有录像，只有被扭曲的我的真实经历。我知道对于您位高权重的张高丽副总理来说，你说过你不怕。但即使是以卵击石，飞蛾扑火自取灭亡的我也会说出和你的事实。以你的智商某略你一定否认或者可以反扣给我，你可以如此玩世不恭。你总说希望你母亲在天可以保佑你，我是一个坏女孩不配为人母，你为人父也有儿有女，我问过你就算是你的养女你会逼她这么做吗？你今生做的这一切日后心安理得的去面对你的母亲吗？ 我们都很道貌岸然……"}]

**Comment by AutoReplySender** [comment]
谢谢。我看一下哪些语录适合用来回复主贴。
